image/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="home"),
    path("images/<uuid:image_id>/download",
         views.download_image, name="download_image")
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("image.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

image/models.py
from django.db import models
from django.core.files.uploadedfile import InMemoryUploadedFile
import uuid
from enhancer.Enhancer import Deblurrer, Denoiser, SuperResolver
from PIL import Image as _Image
from io import BytesIO
import sys
# Create your models here.


class Image(models.Model):
    unique_id = models.UUIDField(
        default=uuid.uuid4, editable=False, primary_key=True)
    name = models.TextField(default='')
    image = models.ImageField(upload_to="images")
    deblur = models.BooleanField(default=False)
    denoise = models.BooleanField(default=False)
    super_resolve = models.BooleanField(default=False)
    deblurrer = Deblurrer()
    denoiser = Denoiser()
    sr = SuperResolver()

    def __str__(self):
        return str(self.unique_id)

    def save(self):
        img = _Image.open(self.image).convert('RGB')

        img_enhanced = img

        if self.denoise:
            img_enhanced = self.denoiser.enhance(img_enhanced)
        if self.deblur:
            img_enhanced = self.deblurrer.enhance(img_enhanced)
        if self.super_resolve:
            img_enhanced = self.sr.enhance(img_enhanced)

        # transform image here
        output = BytesIO()
        im = _Image.fromarray(img_enhanced)

        # im = img.resize((400, 400))

        im.save(output, format='JPEG', quality=100)
        output.seek(0)
        self.image = InMemoryUploadedFile(output, 'ImageField', str(
            self.unique_id) + ".jpg", 'image/jpeg', sys.getsizeof(output), None)
        self.name = "%s.jpg" % self.image.name.split(
            '.')[0]

        super(Image, self).save()

image/views.py
from django.shortcuts import render, redirect
from wsgiref.util import FileWrapper
from django.http import HttpResponse
import mimetypes
from .form import ImageForm
from .models import Image
import os

# Create your views here.


def index(request):
    if request.method == "POST":
        form = ImageForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            obj = form.instance
            return render(request, "index.html", {"obj": obj, "form": ImageForm()})
    else:
        form = ImageForm()
    return render(request, "index.html", {"form": form})


def download_image(request, image_id):
    if request.method == 'GET':
        img = Image.objects.get(unique_id=image_id)
        filePath = './media/images/' + str(img.name)
        # img.file returns full path to the image
        wrapper = FileWrapper(open(filePath, 'rb'))
        content_type = mimetypes.guess_type(
            img.name)[0]  # Use mimetypes to get file type
        print('content_type', content_type)
        response = HttpResponse(wrapper, content_type=content_type)
        response['Content-Length'] = os.path.getsize(filePath)
        response['Content-Disposition'] = "attachment; filename=%s" % img.name
        return response

image/templates/index.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="icon" type="image/*" href="{% static 'icon.svg'%}"/>
    <title>Image Restoration</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #1962a7; position: sticky; top: 0;">
      <a class="navbar-brand my-nav" href="#">
        <img src="{% static 'icon.svg'%}" />
        <h3 style="margin-bottom: 0; color: white;">Image Restoration</h3>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <!-- <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
        </ul>
      </div> -->
    </nav>
    <div class="container my-container">
      <form action="." id="form" method="post" enctype="multipart/form-data"
        style="margin-right: 20px;">

        {% csrf_token %}
        <!-- {{form.as_p}} -->
        <div class="field-wrapper">
          <label for="id_image" class="upload-label">
            <span>Choose Image</span>
            <img class="upload-icon" src="{% static 'upload-file.svg'%}" />
          </label>
          {{form.image}}

          <div class="checkbox-list"> 
            <span>
              {{form.deblur}}
              <label for="id_deblur">
                Deblur
              </label>
            </span>

            <span>
              {{form.denoise}}
              <label for="id_denoise">
                Denoise
              </label>
            </span>

            <span>
              {{form.super_resolve}}
              <label for="id_super_resolve">
                Super Resolve
              </label>
            </span>
          </div>
        </div>
        <div style="text-align: right; margin-top: 10px;">
          <button class="btn btn-lg my-btn" onclick="handleReload(event)" style="padding: 6px 15px 6px 30px;">
            <img src="{% static 'icon.svg'%}" />
          </button>
          <button id="submit_form" class="btn btn-lg my-btn" onclick="handleSubmit(event)">
            Upload
          </button>
        </div>
      </form>

      <div> 
        {% if obj %}
          <div style="margin: 20px 0; max-width: 800px;">
            <h3 style="display: flex; align-items: center;">
              Succesfully uploaded 
              <button class="btn btn-lg my-btn" style="margin-left: 15px;">
                <a class="download-url" href="/images/{{obj.unique_id}}/download">Download</a>
              </button>
            </h3>
            <!-- {{obj.image}} -->
            <img src="{{ obj.image.url}}"
              alt="image" class="image-uploaded" />
          </div>
        {% endif %}

        <div style="max-width: 800px;" id="preview-container">
          <h3 id="preview-title">Preview</h3>
          <img src="" id="image-preview"
            alt="image" class="image-uploaded" />
        </div>
      </div>

        <!-- {% for x in img %}
          {% if forloop.first %}<div class="row ">{% endif %}
            <div class="col-lg-4 col-md-4 col-12" >
              <div class="text-center mt-2">
                <img src="{{x.image.url}}" height="70%" width="70%" class="img-thumbnail" alt="...">
                <h2 class="text-center" >{{x.caption}}</h2>
              </div>
          </div>
          {% if forloop.counter|divisibleby:3 %}
          </div>
          <div class=row>{% endif %}
            {% if forloop.last %}</div>{% endif %}
        {% endfor %} -->
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
    <script src="{% static 'index.js' %}"></script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    -->
  </body>
</html>